version: "3"

services:
  frontend:
    container_name: front-ayomi
    build:
      context: .
      dockerfile: client/Dockerfile
    ports:
      - 5173:5173
    stdin_open: true
    tty: true
    volumes:
     - type: bind
       source: ./client
       target: /app

  backend:
    container_name: back-ayomi
    build: 
      context: .
      dockerfile: server/Dockerfile
    ports:
      - 8000:80
    volumes:
     - type: bind
       source: ./server
       target: /app

  db:
    image: mariadb:10.6.10-focal
    container_name: ayomi_mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: ayomi
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db:/var/lib/mysql
    ports:
      - 3306:3306

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: ayomi_phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    volumes:
      - phpmyadmin:/sessions
    ports:
      - 8080:80
    depends_on:
      - db

volumes:
  db:
  phpmyadmin:
  frontend:
